### ISSUE TITLE
消息推送接收问题

### ISSUE THREAD

**Issue by yanlun0323** [duckchat/gaga#20]
消息推送过来，客户端接收消息比较慢，请问是为什么？

**Comment by yanlun0323** [comment]
http://open.akaxin.com:5208/?action 推送的这个地址现在访问失效了，请问有新的地址提供吗？

**Comment by sisishiliu** [comment]
HTTP轮询机制，与用户所在的场景有关。

长链接机制，需要你主动在服务器端开启。
