### ISSUE TITLE
Login/Register page, MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by coddec** [duckchat/gaga#32]
网页登陆/注册页面，浏览器console返回，导致无法登陆与注册

Refused to execute script from 'https://example.com/index.php?action=page.siteConfig&callback=zalyLoginConfig' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by sisishiliu** [comment]
请问你是什么浏览器？

**Comment by coddec** [comment]
> 请问你是什么浏览器？

是chrome，不过firefox效果也一样，Edge的话也是一样无法注册。
不知道是不是和apache的几个header有关

content-security-policy: default-src: https:; object-src 'self'
strict-transport-security: max-age=63072000; includeSubdomains; preload
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block

是的话希望能兼容，这些是安全设置

谢谢

**Comment by sisishiliu** [comment]
明白，我们查一下

**Comment by coddec** [comment]
> 明白，我们查一下

谢谢！

😄

**Comment by sisishiliu** [comment]
我对你github里的项目很感兴趣，根据你Github主页留的链接发了一个好友请求，回一个联系方式？
